name: Teste Python

on:
  workflow_dispatch:

jobs:
  executar-python:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Verificar Python
        run: python --version

      - name: Executar Python
        run: python teste.py
