name: Teste Relatório SSW

on:
  push:
    branches:
      - Relatorio-Main

  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  teste-gatilhos:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar gatilho
        run: |
          echo "========================================"
          echo "TESTE DO GITHUB ACTIONS"
          echo "========================================"
          echo "Gatilho utilizado:"
          echo "${{ github.event_name }}"
          echo ""
          echo "Branch:"
          echo "${{ github.ref_name }}"
          echo ""
          echo "Commit:"
          echo "${{ github.sha }}"
          echo ""
          echo "Data/hora UTC:"
          date -u
          echo "========================================"
