name: Relatório SSW

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * 1-5"

jobs:
  teste-agendamento:
    runs-on: ubuntu-latest

    steps:
      - name: Testar agendamento
        run: |
          echo "========================================"
          echo "O AGENDAMENTO FUNCIONOU!"
          echo "========================================"
          echo "Data e hora UTC:"
          date -u
          echo "========================================"
